config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'gossips#index'

  resources :gossips
  resources :users
  resources :cities
  resources :comments
  resources :sessions

  resources :gossips do
    resources :comments
  end

# WE USE THE OLD METHOD TO SHOW STATIC PAGES (no need to have index, show, create...)
  get "/team", to: "static_pages#team"
  get "/contact", to: "static_pages#contact"

  # THIS IS THE OLD METHOD, WE'RE NOW USING THE ABOVE METHOD ie: resources
    # get "/", to: "welcome#home"
    # get "/welcome/:id", to: "welcome#greet"
    # get "/gossip/:id", to: "gossip#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, :as => :likeable, dependent: :destroy
  has_many :comments, :as => :commentable, dependent: :destroy
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, :length => { :minimum => 3, :maximum   => 14 }
  validates :content, :presence => true
  belongs_to :user
  has_many :comments, :as => :commentable, dependent: :destroy
  has_many :join_table_gossip_tags
  has_many :tags, through: :join_table_gossip_tags
  has_many :likes, :as => :likeable, dependent: :destroy
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_table_message_recipients
  has_many :recipients, class_name: "User", through: :join_table_message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :join_table_message_recipients
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinTableMessageRecipient"
  has_many :likes
  has_many :comments
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end
  def show
    @city = City.find(params[:id])
    @gossips = Gossip.all
  end
  def new

  end
  def create
  end
  def edit
  end
  def update
  end
  def destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new
  @comment = Comment.new
  @gossip = Gossip.find(params[:gossip_id])

  puts "n" * 100
end

  def create
    @gossip = Gossip.find(params[:gossip_id])
    puts "c" * 100
    # @gossip = Gossip.create(:user => User.all.sample, :title => params[:title], :content => params[:content])
    # redirect_to root_path
      #@comment = Comment.new(:user_id => User.all.sample, :commentable_type => "Gossip", :commentable_id => params[:gossip_id], :content => params[:content]) # avec xxx qui sont les données obtenues à partir du formulaire
      @comment = Comment.new(:user => User.all.sample, :commentable => @gossip, :content => params[:content])
      if @comment.save # essaie de sauvegarder en base @gossip
        redirect_to gossip_path(@gossip.id) # si ça marche, il redirige vers la page d'index du site
      else
        # sinon, il render la view new (qui est celle sur laquelle on est déjà)
        render new_gossip_path
      end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
  end

  def new
    @gossip = Gossip.new
  end

  def create
    # @gossip = Gossip.create(:user => User.all.sample, :title => params[:title], :content => params[:content])
    # redirect_to root_path
      @gossip = Gossip.new(:user => User.all.sample, :title => params[:title], :content => params[:content]) # avec xxx qui sont les données obtenues à partir du formulaire

      if @gossip.save # essaie de sauvegarder en base @gossip
        redirect_to root_path # si ça marche, il redirige vers la page d'index du site
      else
        # sinon, il render la view new (qui est celle sur laquelle on est déjà)
        render new_gossip_path
      end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
     if @gossip.update(gossip_params)
        redirect_to gossip_path
    else
        render :edit
    end
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
end


  def destroy
  @gossip = Gossip.find(params[:id])
  @gossip.destroy
  redirect_to gossips_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def index
        # @sessions = Session.all
    end
    def show
        @session = Session.find(params![:id])
    end
    def new
        # @session = Session.new
    end
    def create
    end
    def edit
    end
    def update
    end
    def destroy
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def show
    @user = User.find(params[:id])
  end
  def new
    
  end
  def create
  end
  def edit
  end
  def update
  end
  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4"><%= @city.name %> </h1>
  <p class="lead">View juicy gossips from <%= @city.name %>.</p>
</div>

<br>

<div class="container">
  <div class="row">
    <% @city.users.each do |u| %>
    <%   u.gossips.each do |g| %>
      <div class="col-6">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-body">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1"><%= u.first_name %></h5>
                  <small></small>
                </div>
                <p class="card-text"><%= g.title %></p>
                <a <%= link_to "View", gossip_path(g.id)%> </a>
              </div>
            </div>
          </div>
        </div><br>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">View Gossip</h1>
  <p class="lead">Here's a juicy gossip for you. Enjoy!</p>
</div>

<br>

<div class="container">
<div class="card">
  <h5 class="card-header">
    <a <%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %> • <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %> </a>
  </h5>
    <div class="card-body">
      <h5 class="card-title"><%= @gossip.title %> </h5>
      <p class="card-text"><%= @gossip.content %></p>
      <a <%= link_to "Edit", edit_gossip_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>
      <a <%= link_to "Delete", gossip_path(@gossip.id), :class => "btn btn-outline-danger", :method => :delete%> </a>
      <a <%= link_to "Comment", new_gossip_comment_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>


    </div>
  </div>
</div>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Add a Comment</h5>
          <%= form_tag gossip_comments_path do %>
          <div class="form-group">
            <%= text_area_tag :content, placeholder = "Add a comment here...", class: 'form-control no-border' %>
          </div>
            <%= submit_tag "Comment", class: 'btn btn-default btn btn-primary' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<br>

<div class="container">
  <div class="container">
  <% @gossip.comments.each do |n| %>
  <div class="media">
    <!-- <%= image_tag "user.png", :size => "20x20" %> -->
    <div class="media-body">
      <h5 class="mt-0"><%= n.user.first_name %></h5>
      <%= n.content %>
    </div>
  </div> <br>
  <% end %>
</div>
</div>

app/views/gossips/edit.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Edit Gossip</h1>
  <p class="lead">Edit your juicy gossip.</p>
</div>

<br>

<div class="container">
<%= form_for @gossip do |f| %>
  <div class="form-group">
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit"class="btn btn-success">Update</button>
  </div>
<% end %>
</div>

app/views/gossips/index.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">The Gossip Project</h1>
  <p class="lead">All the juicy gossips from THP Session 9. Stay tuned!</p>
</div>

<div class="row justify-content-center">
  <a class="btn btn-success btn-lg" <%= link_to "Create New Gossip", new_gossip_path %></a>
</div> <br><br>

<div class="container">
  <div class="row">
    <% @gossips.each do |n| %>
      <div class="col-6">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-body">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1"><%= n.user.first_name %></h5>
                  <small></small>
                </div>
                <p class="card-text"><%= n.title %></p>
                <a <%= link_to "View", gossip_path(n.id)%> </a>
              </div>
            </div>
          </div>
        </div><br>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/new.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">New Gossip</h1>
  <p class="lead">Add your own juicy gossip.</p>
</div>

<br>

<div class="container">
  <%= form_tag gossips_path do %>
  <div class="form-group">
    <%= text_field_tag :title, placeholder = "Title", class: 'form-control', autofocus: true %>
  </div>
  <div class="form-group">
    <%= text_area_tag :content, placeholder = "Content", class: 'form-control' %>
  </div>
  <%= submit_tag "Submit", class: 'btn btn-default btn btn-success' %>
</div>
<% end %>

app/views/gossips/show.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">View Gossip</h1>
  <p class="lead">Here's a juicy gossip for you. Enjoy!</p>
</div>

<br>

<div class="container">
<div class="card">
  <h5 class="card-header">
    <a <%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %> • <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %> </a>
  </h5>
    <div class="card-body">
      <h5 class="card-title"><%= @gossip.title %> </h5>
      <p class="card-text"><%= @gossip.content %></p>
      <div class="d-flex w-100 justify-content-between">
      <a <%= link_to "Comment", new_gossip_comment_path(@gossip.id), :class => "btn btn-primary" %> </a>
      <div>
      <a <%= link_to "Edit", edit_gossip_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>
      <a <%= link_to "Delete", gossip_path(@gossip.id), :class => "btn btn-outline-danger", :method => :delete%> </a>
    </div>
  </div>
</div>
</div>

<br>

<div class="container">
  <div class="container">
  <% @gossip.comments.each do |n| %>
  <div class="media">
    <!-- <%= image_tag "user.png", :size => "20x20" %> -->
    <div class="media-body">
      <h5 class="mt-0"><%= n.user.first_name %></h5>
      <%= n.content %>
    </div>
  </div> <br>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4"><%= @user.first_name %> <%= @user.last_name %></h1>
  <p class="lead">View gossiper profils here.</p>
</div>

<br>

<div class="container">
<div class="card">
  <h5 class="card-header">
    <%= @user.first_name %> <%= @user.last_name %>
  </h5>
  <div class="card-body">
    <p class="card-text"><%= @user.description %></p>
    <li> email: <%= @user.email %> </li>
    <li> age: <%= @user.age %> </li>
    <li>  city: <%= @user.city.name %> </li>
    <li> <%= link_to "#{@user.city.name}", city_path(@user.city.id) %> </li>
  </div>
</div>
</div>